ContactProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

import contactus

urlpatterns = [
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'contact/', include('contactus.urls', namespace='contactus')),
    url(r'contact-admin/', include('contactusadmin.urls', namespace='contact_admin')),
]

contactus/urls.py
from django.conf.urls import url, include

from contactus import views

urlpatterns = [

    url(r'^$', views.ContactUsCreateView.as_view(), name="contact-us"),
    url(r'^thankyou/$', views.ContactUsThankYouTemplateView.as_view(), name="thank-you"),
    url(r'^contact-view/(?P<pk>\d+)/$', views.ContactUsDetailView.as_view(), name="view-contact"),
    url(r'^contact-update/(?P<pk>\d+)/$', views.ContactUsUpdateView.as_view(), name="update-contact"),
    url(r'^contact-delete/(?P<pk>\d+)/$', views.ContactUsDeleteView.as_view(), name="delete-contact"),

]

contactusadmin/urls.py
from django.conf.urls import url, include

from contactusadmin import views

urlpatterns = [

    url(r'^$', views.ContactsListView.as_view(), name="list-contacts"),
    url(r'^contacts-export/$', views.export_contact_to_pdf, name="export-contact"),

]

contactus/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class ContactModel(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=100)
    query = models.TextField()
    created_timestamp = models.DateTimeField(auto_now=True)
    updated_timestamp = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

contactusadmin/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

contactus/forms.py
from django import forms
from django.forms import TextInput

from contactus.models import ContactModel


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        fields = '__all__'
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'email': TextInput(attrs={'class': 'form-control'}),
            'phone': TextInput(attrs={'class': 'form-control'}),
        }

contactus/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView, DeleteView, DetailView

from contactus.forms import ContactUsForm
from contactus.models import ContactModel


class ContactUsCreateView(SuccessMessageMixin, CreateView):
    model = ContactModel
    form_class = ContactUsForm
    template_name = 'contactus_form.html'
    success_message = "Thank you for you valueable time"
    success_url = reverse_lazy('thank-you')

class ContactUsUpdateView(UpdateView):
    model = ContactModel
    form_class = ContactUsForm
    template_name = 'contactus_form.html'

class ContactUsThankYouTemplateView(TemplateView):
    template_name = 'contactus_thankyou.html'


class ContactUsDetailView(DetailView):
    model = ContactModel
    template_name = 'view-contact.html'
    context_object_name = 'contact'


class ContactUsDeleteView(DeleteView):
    model = ContactModel
    template_name = 'contactmodel_confirm_delete.html'
    success_url = reverse_lazy('contact_admin:list-contacts')

contactusadmin/views.py
import os
import time

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMessage

from django.template.loader import render_to_string
from django.views.generic import ListView
from weasyprint import HTML
import zipfile

from ContactProject.celery import app
from contactus.models import ContactModel


class ContactsListView(LoginRequiredMixin, ListView):
    model = ContactModel
    template_name = 'contact_list.html'
    context_object_name = 'contacts'


@app.task
def export_contact_to_pdf(request):
    contacts = ContactModel.objects.all()
    for contact in contacts:
        html_string = render_to_string('contact_pdf_template.html', {'contacts': contact})

        html = HTML(string=html_string)
        pdf_file_name = "Exports/%d-%s.pdf" %(int(time.time()), contact.name)
        html.write_pdf(target=pdf_file_name)

    zipf = zipfile.ZipFile('Exports.zip', 'w', zipfile.ZIP_DEFLATED)
    for root, dirs, files in os.walk("Exports"):
        for file in files:
            zipf.write(os.path.join(root, file))

    html_content = "New pdf exports of existing contacts"
    email = EmailMessage("my subject", html_content, "pdf-contacts-export@admin.com", ["admin@admin.com"])
    email.content_subtype = "html"

    fd = open('manage.py', 'r')
    email.attach('manage.py', fd.read(), 'text/plain')

    res = email.send()

contactus/templates/contactmodel_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p class="alert alert-danger">Are you sure you want to delete informations by "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

contactus/templates/contactus_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
    <div class="col-md-4 col-md-offset-4">
        <form method="post" action="{% url 'contactus:contact-us' %}">
        {% csrf_token %}
    {%  crispy form %}
    <input type="submit" class="btn btn-info" />
    </form>
</div>
</div>

{% endblock content  %}

contactus/templates/contactus_thankyou.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact Us</title>
</head>
<body>
<h2>Thank you for the information.</h2>
</body>
</html>

contactus/templates/view-contact.html
{% extends 'base.html' %}
{% block content %}
Name: {{ contact.name }}
Phone/Mobile: {{ contact.phone }}
Email: {{ contact.email }}
Query: {{ contact.query }}
{% endblock content %}

contactusadmin/templates/contact_list.html
{% extends 'base.html' %}
{% block content %}
    <ul class="list-group">
{% for contact in contacts %}

      <li class="list-group-item">
            {{ contact.name }}
            <a class="btn btn-info" href="{% url 'contactus:view-contact' pk=contact.id %}">View</a>
            <a class="btn btn-info" href="{% url 'contactus:update-contact' pk=contact.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'contactus:delete-contact' pk=contact.id %}">Delete</a>
      </li>

{% endfor %}
        </ul>
<a class="btn btn-info" href="{% url 'contact_admin:export-contact' %}">Export</a>
{% endblock content %}

contactusadmin/templates/contact_pdf_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <div class="col-md-6 col-md-offset-3">
        Name: {{ contact.name }}
        Phone/Mobile: {{ contact.phone }}
        Email: {{ contact.email }}
        Query: {{ contact.query }}
    </div>

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Ayulogic</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="username" name="username" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" name="password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">

{% block content %}
{% endblock %}

      </div>
    </div>
</body>
</html>